### PR TITLE
refactor: unify organism names and refactor their config

### LINKED ISSUE #109: Notifications: Revisit naming of instance names
The currently occur in `Subscriptions.kt` and `SubscriptionTable.tsx`. They have different casing. Unify them

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #109

### CODE REVIEW

**Review by JonasKellerer — APPROVED** [review]
LGTM.
I am interessed where this will go: if we need to add more to the config in the future, or how/if we will set the specific values of colors for the different organisms.

**Review by JonasKellerer — CHANGES_REQUESTED** [review]
I think you missed in `src/pages/subscriptions/index.astro` the dummy values on the website. For me `http://localhost:4321/subscriptions` shows an error.

**Comment by fengelniederhammer** [comment]
> I think you missed in `src/pages/subscriptions/index.astro`

Thanks for catching this. I just checked: `npm run check-astro` would have caught it, but we don't run it in CI, since it throws too many errors. We should do it now... #11

**Review by JonasKellerer — APPROVED** [review]
LGTM

**Pull request merged**
