### PR TITLE
feat(website): add clade filter and table to H5N1

### LINKED ISSUE #179: Add clades for H5N1
We can add clade labels using
1.  [LABEL](https://wonder.cdc.gov/amd/flu/label/) built by the CDC to assign avian flu clades

2. [nextclade H5Nx dataset](https://github.com/nextstrain/nextclade_data/blob/master/data/community/moncla-lab/iav-h5/ha/2.3.2.1/README.md) is available here (it includes the 2014 clade split: see https://onlinelibrary.wiley.com/doi/full/10.1111/irv.12324, seems to be the last official WHO clade assignment), it was shown to be close to the CDC tool LABEL and we already use nextclade for other clades so it should be easy to add.

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #179

### Screenshot

Adding the filter:
grafik

Adding the table to aggregated by clade:
grafik

### CODE REVIEW

**Review by JonasKellerer — APPROVED** [review]
LGTM

For Mpox we have something like "None" when there is no clade. For H5N1 it seems there is no such thing but a blank. Is this something we want? I think this would need to be changed in the preprocessing.

**Comment by anna-parker** [comment]
Thanks! I just tested it locally and the list looks very long and a bit hard to use as it isn't sorted: 
image
could we maybe sort the clades alphabetically?

**Comment by fengelniederhammer** [comment]
> could we maybe sort the clades alphabetically?

That would be something we need to do in the components. It would probably be good to sort it, but also rather low prio (IMO)

**Comment by fengelniederhammer** [comment]
> For Mpox we have something like "None" when there is no clade. For H5N1 it seems there is no such thing but a blank. Is this something we want? I think this would need to be changed in the preprocessing.

Yes, we would need to do that somewhere in our Loculus setup...

**Comment by anna-parker** [comment]
I created an issue for sorting the output: https://github.com/GenSpectrum/dashboard-components/issues/514 do think that will make the UI more user friendly

**Pull request merged**
